# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 18a9c4b0b8fd073c293de0d9d63bee2894b8ae4a

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/11/
Content-Type: application/json
Authorization: Token 18a9c4b0b8fd073c293de0d9d63bee2894b8ae4a

{
  "status": "OPEN"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2024-10-01&ordering=created_at
Content-Type: application/json

###

GET {{baseUrl}}/advertisements/?status=OPEN
Content-Type: application/json