# Generated by Django 5.1 on 2024-08-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_scope_is_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название тэга'),
        ),
    ]
